---
- hosts: all
  become: true
    gather_facts: no
  tasks:
-       name: install latest version of Apache
yum:
  name: "(( item }}"
  state: latest
      with_items:
-       httpd
-       httpd-tools
  
  -  name: create web content file
     copy:
       content: "Yay!  Simply deployed Apache webserver …"
       dest: /var/www/html/index.html
  
  - name: firewall enabled and running
    service: 
      enabled: true
      name: firewalld
      state: started
  
  - name: firewalld persists httpd service
    firewalld:
      immediate: yes
      permanent: true
      service: http
      state: enabled

  - name: httpd enabled and running 
    service: 
      name: httpd
      state: started
      enabled: true
Join
