- hosts: all
  become: True
  tasks:
   - name: Install all the packages
     dnf:
       name: '{{ item }}'
       state: present
       update_cache: True
     with_items:
     httpd
     php
     vsftpd
