---
- hosts: all
  tasks:
  - name: Package installation
    yum:
      name:
        - sysstat
        - httpd
        - mariadb-server
        - vim
        - curl
        - unzip
      state: latest
